### ISSUE TITLE
Prohibido descargar archivos

### ISSUE THREAD

**Issue by flgomezc** [ComputoCienciasUniandes/FISI2026-201910#1]
Binder no permite realizar la descarga de archivos al hacer click derecho --> descargar.

Funciona cuando se hace click derecho --> abrir en pestaña nueva.

**Comment by forero** [comment]
El problema es jupyter-lab. Deshabilité jupyter-lab para dejar la interfaz antigua de jupyter. Esa sí permite bajar archivos.
